'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

// =====================================================================
// ACE suit cards — the transparent-glass theme's living backdrop.
// ---------------------------------------------------------------------
// Hundreds of ACE playing-card suits drift UPWARD through the glass,
// generated by JavaScript (random suit / size / color / timing per ace)
// and animated purely with CSS keyframes. Shapes are ONLY the four card
// suits — Ace of Spades, Ace of Hearts, Ace of Diamonds, Ace of Clubs —
// carved as crisp inline-SVG silhouettes, colored like REAL pink petals
// (deep-pink edge → soft pink → white base multi-stop gradients + a
// glossy radial sheen), with rare white/magenta/violet/black accents. Two depths: most aces rise
// BEHIND the app (z -1, frosted cards blur them) and a front subset
// drifts ABOVE the content (z 30) — but ONLY ever over TEXT: a JS
// media-avoidance loop hides any front ace whose center crosses an
// <img> or <video>, so photos and clips always stay unobstructed.
// =====================================================================

// the four ACES — and nothing else. Each is a single SVG path (the club
// packs its three lobes + stem into one path of four subpaths) drawn in
// a 0 0 100 100 viewBox.
const SUIT_PATHS = {
  spades:
    'M50 5 C50 5 10 45 10 63 C10 75 20 83 31 83 C38 83 44 80 48 74 C46 85 41 93 32 97 L68 97 C59 93 54 85 52 74 C56 80 62 83 69 83 C80 83 90 75 90 63 C90 45 50 5 50 5 Z',
  hearts:
    'M50 92 C28 74 8 57 8 35 C8 20 19 9 33 9 C41 9 47 13 50 20 C53 13 59 9 67 9 C81 9 92 20 92 35 C92 57 72 74 50 92 Z',
  diamonds:
    'M50 4 C57 19 70 36 87 50 C70 64 57 81 50 96 C43 81 30 64 13 50 C30 36 43 19 50 4 Z',
  clubs:
    'M29 30 a21 21 0 1 0 42 0 a21 21 0 1 0 -42 0 M9 59 a20 20 0 1 0 40 0 a20 20 0 1 0 -40 0 M51 59 a20 20 0 1 0 40 0 a20 20 0 1 0 -40 0 M45 62 C45 76 41 88 33 96 L67 96 C59 88 55 76 55 62 Z',
} as const

type Suit = keyof typeof SUIT_PATHS
const SUITS = Object.keys(SUIT_PATHS) as Suit[]

// gradient fills shared by every floating ace (defined once, referenced
// by id) — the PINK PETAL family uses realistic multi-stop gradients:
// deep pink at the petal edge, soft pink mid, near-white at the base,
// like light passing through a real petal. Solids bypass the defs.
const SUIT_GRADIENTS: Record<string, [string, string][]> = {
  'grad-petal-sakura': [['0%', '#fff6fa'], ['45%', '#ffc2dc'], ['100%', '#ff8fbf']],
  'grad-petal-blush': [['0%', '#ffffff'], ['50%', '#ffd0e2'], ['100%', '#ff9fc4']],
  'grad-petal-rose': [['0%', '#ffeef5'], ['45%', '#ffa8c9'], ['100%', '#ff6fa5']],
  'grad-petal-hot': [['0%', '#ffffff'], ['50%', '#ff9fc4'], ['100%', '#ff4f98']],
  'grad-petal-peony': [['0%', '#fff0f6'], ['45%', '#ffb3d1'], ['100%', '#e75c9c']],
  'grad-petal-cotton': [['0%', '#ffffff'], ['55%', '#ffdce9'], ['100%', '#ffb6d3']],
  'grad-magenta-white': [['0%', '#ffffff'], ['100%', '#ff4fd8']],
  'grad-white-violet': [['0%', '#ffffff'], ['100%', '#a855f7']],
  'grad-silver': [['0%', '#e8e8ef'], ['100%', '#71717d']],
  'grad-charcoal': [['0%', '#3b3b46'], ['100%', '#0b0b10']],
}

// unique palette — dominated by the PINK PETAL family (weighted ~3 of
// every 4 aces): sakura, blush, rose, hot-pink, peony and cotton petals,
// each a pink→white gradient with a matched rosy glow; a rare pure
// white / magenta-white / violet / black ace still slips in as an accent
const ACE_COLORS: { fill: string; glow: string }[] = [
  { fill: 'url(#grad-petal-sakura)', glow: 'rgba(255,143,191,0.5)' },
  { fill: 'url(#grad-petal-sakura)', glow: 'rgba(255,143,191,0.5)' },
  { fill: 'url(#grad-petal-blush)', glow: 'rgba(255,159,196,0.5)' },
  { fill: 'url(#grad-petal-blush)', glow: 'rgba(255,159,196,0.5)' },
  { fill: 'url(#grad-petal-rose)', glow: 'rgba(255,111,165,0.5)' },
  { fill: 'url(#grad-petal-rose)', glow: 'rgba(255,111,165,0.5)' },
  { fill: 'url(#grad-petal-hot)', glow: 'rgba(255,79,152,0.5)' },
  { fill: 'url(#grad-petal-hot)', glow: 'rgba(255,79,152,0.5)' },
  { fill: 'url(#grad-petal-peony)', glow: 'rgba(231,92,156,0.5)' },
  { fill: 'url(#grad-petal-peony)', glow: 'rgba(231,92,156,0.5)' },
  { fill: 'url(#grad-petal-cotton)', glow: 'rgba(255,182,211,0.5)' },
  { fill: 'url(#grad-petal-cotton)', glow: 'rgba(255,182,211,0.5)' },
  // rare accents — kept from the earlier monochrome/violet look
  { fill: '#ffffff', glow: 'rgba(255,255,255,0.55)' }, // pure white ace
  { fill: 'url(#grad-magenta-white)', glow: 'rgba(255,79,216,0.4)' }, // magenta-white ace
  { fill: '#a855f7', glow: 'rgba(168,85,247,0.5)' }, // violet ace — the purple tip
  { fill: '#0b0b10', glow: 'rgba(11,11,16,0.35)' }, // black ace
]

// three sway flavors keep aces from moving in lock-step
const SWAY_KEYS = ['ace-leaf-sway-a', 'ace-leaf-sway-b', 'ace-leaf-sway-c'] as const

interface AceSpec {
  left: number // 0–100 %
  size: number // px
  aspect: number // suits are near-square; keep subtle variety
  rise: number // seconds bottom→top
  delay: number // negative offset so the sky is already full
  sway: number // seconds per sway cycle
  swayAmp: number // px horizontal drift
  opacity: number
  suit: Suit
  color: { fill: string; glow: string }
  swayKey: (typeof SWAY_KEYS)[number]
}

function randomAce(): AceSpec {
  const rise = 11 + Math.random() * 15 // 11–26 s per ascent
  return {
    left: Math.random() * 100,
    size: 9 + Math.random() * 31, // 9–40 px — all size classes
    aspect: 0.95 + Math.random() * 0.2, // suits read best near-square
    rise,
    delay: -Math.random() * rise, // already mid-flight on mount
    sway: 2.4 + Math.random() * 3.8,
    swayAmp: 12 + Math.random() * 40,
    opacity: 0.45 + Math.random() * 0.5,
    suit: SUITS[Math.floor(Math.random() * SUITS.length)],
    color: ACE_COLORS[Math.floor(Math.random() * ACE_COLORS.length)],
    swayKey: SWAY_KEYS[Math.floor(Math.random() * SWAY_KEYS.length)],
  }
}

/** Watch <html data-theme> so the layer appears/disappears with the theme. */
function usePremiumThemeActive(): boolean {
  const [active, setActive] = useState(false)
  useEffect(() => {
    const html = document.documentElement
    const sync = () => setActive(html.dataset.theme === 'premium')
    sync()
    const observer = new MutationObserver(sync)
    observer.observe(html, { attributes: true, attributeFilter: ['data-theme'] })
    return () => observer.disconnect()
  }, [])
  return active
}

function GradientDefs() {
  return (
    <svg width="0" height="0" style={{ position: 'absolute' }} aria-hidden="true">
      <defs>
        {Object.entries(SUIT_GRADIENTS).map(([id, stops]) => (
          <linearGradient key={id} id={id} x1="0%" y1="0%" x2="100%" y2="100%">
            {stops.map(([offset, color]) => (
              <stop key={offset} offset={offset} stopColor={color} />
            ))}
          </linearGradient>
        ))}
        {/* glossy light-catch sheen laid over every petal — the touch
            that makes the gradients read as real petals, not flat fills */}
        <radialGradient id="grad-petal-sheen" cx="30%" cy="22%" r="80%">
          <stop offset="0%" stopColor="#ffffff" stopOpacity="0.75" />
          <stop offset="45%" stopColor="#ffffff" stopOpacity="0.2" />
          <stop offset="100%" stopColor="#ffffff" stopOpacity="0" />
        </radialGradient>
      </defs>
    </svg>
  )
}

/**
 * Media avoidance for the FRONT ace layer: ~8×/s, hide any front ace
 * whose center sits inside an <img>/<video> rect (reads batched before
 * writes — no layout thrash). Front aces may pass over text, but photos
 * and videos are never covered. Runs only while the front layer exists.
 */
function MediaAvoidance({
  layerRef,
}: {
  layerRef: React.RefObject<HTMLDivElement | null>
}) {
  useEffect(() => {
    let raf = 0
    let last = 0
    const tick = (t: number) => {
      raf = requestAnimationFrame(tick)
      if (t - last < 120) return // throttle to ~8 Hz
      last = t
      const layer = layerRef.current
      if (!layer) return
      // READ phase 1 — every rendered img/video rect
      const mediaRects: { l: number; r: number; t: number; b: number }[] = []
      document.querySelectorAll('img, video').forEach((m) => {
        const r = m.getBoundingClientRect()
        if (r.width > 2 && r.height > 2)
          mediaRects.push({ l: r.left, r: r.right, t: r.top, b: r.bottom })
      })
      // READ phase 2 — classify front aces by center-point hit test
      const toAdd: HTMLElement[] = []
      const toRemove: HTMLElement[] = []
      layer.querySelectorAll<HTMLElement>('.ace-leaf-fall').forEach((ace) => {
        const r = ace.getBoundingClientRect()
        const cx = r.left + r.width / 2
        const cy = r.top + r.height / 2
        let hide = false
        for (const m of mediaRects) {
          if (cx > m.l && cx < m.r && cy > m.t && cy < m.b) {
            hide = true
            break
          }
        }
        if (hide !== ace.classList.contains('ace-avoid-media')) {
          ;(hide ? toAdd : toRemove).push(ace)
        }
      })
      // WRITE phase — flip visibility only where it changed
      toAdd.forEach((el) => el.classList.add('ace-avoid-media'))
      toRemove.forEach((el) => el.classList.remove('ace-avoid-media'))
    }
    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [layerRef])
  return null
}

export function AceLeaves() {
  // themeActive starts false on BOTH server and client, so the first
  // render matches (null) and the portal only mounts after the effect
  // below flips it — no hydration mismatch, no mounted flag needed.
  const themeActive = usePremiumThemeActive()
  const frontLayerRef = useRef<HTMLDivElement | null>(null)

  // "hundreds of ace": 160 aces on desktop, 120 on small screens;
  // ~62% rise behind the app, ~38% drift above the text layer
  const aces = useMemo<AceSpec[]>(() => {
    if (!themeActive) return []
    const count =
      typeof window !== 'undefined' && window.innerWidth < 640 ? 120 : 160
    return Array.from({ length: count }, randomAce)
  }, [themeActive])

  if (!themeActive || aces.length === 0) return null

  const renderAce = (ace: AceSpec, i: number) => (
    <span
      key={`a${i}`}
      className="ace-leaf-fall"
      style={{
        left: `${ace.left}%`,
        animationDuration: `${ace.rise}s`,
        animationDelay: `${ace.delay}s`,
      }}
    >
      <span
        className={`ace-leaf-sway ${ace.swayKey}`}
        style={
          {
            animationDuration: `${ace.sway}s`,
            animationDelay: `${ace.delay / 2}s`,
            '--sway': `${ace.swayAmp}px`,
          } as React.CSSProperties
        }
      >
        <svg
          className={`ace-leaf ace-suit--${ace.suit}`}
          viewBox="0 0 100 100"
          width={ace.size}
          height={ace.size * ace.aspect}
          style={{
            opacity: ace.opacity,
            filter: `drop-shadow(0 0 ${Math.round(ace.size / 2 + 4)}px ${ace.color.glow})`,
          }}
          aria-hidden="true"
        >
          <path d={SUIT_PATHS[ace.suit]} fill={ace.color.fill} />
          <path d={SUIT_PATHS[ace.suit]} fill="url(#grad-petal-sheen)" />
        </svg>
      </span>
    </span>
  )

  const split = Math.floor(aces.length * 0.62)
  const back = aces.slice(0, split)
  const front = aces.slice(split)

  return createPortal(
    <>
      <GradientDefs />
      <div className="ace-leaf-layer" aria-hidden="true">
        {back.map((ace, i) => renderAce(ace, i))}
      </div>
      <div
        className="ace-leaf-layer ace-leaf-layer--front"
        aria-hidden="true"
        ref={frontLayerRef}
      >
        {front.map((ace, i) => renderAce(ace, i))}
      </div>
      <MediaAvoidance layerRef={frontLayerRef} />
    </>,
    document.body
  )
}
